name: Pytest
on: push
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install mclient
        uses: MonetDB/install-monetdb@v0.8
        with:
          start: "false"

      - name: Download jdbcclient jar
        run: curl -sSf -O https://www.monetdb.org/downloads/Java/jdbcclient.jre8.jar

      - name: Check the environment
        run: |
          set -x
          ip link list
          ip addr list
          ip route list
          hostname
          hostname -d
          hostname -f

      - name: Set up throwaway Kerberos environment
        run: sudo ./tests/setup-github-ci-kerberos.sh

      - name: Log in to Kerberos
        run: |
          echo password | kinit testuser
          klist

      - name: Install Python dependencies
        run: sudo apt install build-essential libkrb5-dev && echo ==== && pip3 install --user --upgrade pip && echo ==== && pip install --user --upgrade --group dev .   #pymonetdb cryptography pytest


      - name: Run pytest
        env:
          FORCE_TESTS: all
          TEST_USERS: monetdb=principal:testuser@GITHUB.CI
          TEST_KEYTAB: /etc/monetdb.keytab
          ALT_CLIENT_KEYTAB: /etc/altuser.keytab
          CLASSPATH: jdbcclient.jre8.jar
        run: env ALT_CLIENT_PRINCIPAL="altuser/$(hostname -f)@GITHUB.CI" pytest -v

      - name: Start MonetDB
        run: |
          monetdbd create /tmp/farm
          monetdbd start /tmp/farm
          monetdb create -pmonetdb demo
          monetdb start demo

      - name: Run democlient against real MonetDB in proxy mode
        run: ./democlient.py -v monetdb:///demo

      - name: Switch MonetDB to redirect mode
        run: |
          monetdbd stop /tmp/farm
          monetdbd set forward=redirect /tmp/farm
          monetdbd start /tmp/farm

      - name: Run democlient against real MonetDB in redirect mode
        run: ./democlient.py -v monetdb:///demo
